### ISSUE TITLE
Running some executables fail with MCAmiga but OK with Dopus shell

### ISSUE THREAD

**Issue by necros2k7** [alb42/MCAmiga#1]
Example: running Quake game - error - "Quake render process #80000005"

**Comment by alb42** [comment]
I guess the reason Is that programs like quake need usually HUGE stacks, but MCAmiga does not set a special stack size of starting programs, so the default stacksize is used (If I remember correctly, it's 4k)
I guess one could make a setting to set the stack size.

**Comment by necros2k7** [comment]
Would be great

**Comment by alb42** [comment]
Fixed in 4ef93553288179ba2f62a557f68cf0a8562a986d
